### ISSUE TITLE
Isn't that a little bit annoying though?!

### ISSUE THREAD

**Issue by lipis** [FarhadG/repo-card#1]
<img width="944" alt="screen shot 2015-11-27 at 21 53 46" src="https://cloud.githubusercontent.com/assets/125676/11448062/6eca2e98-9551-11e5-8790-f399ad90047c.png">

**Comment by FarhadG** [comment]
Thanks for the comment, @lipis.

Haha, yea it is, but this is simply due to my poor theme :). I'd imagine a better theme that uses media queries would be better for something like this.

I would like to have the ability to also animate the card based on some interaction ('scroll', etc.).

I'd like to hear your opinion on improving this...

**Comment by lipis** [comment]
To be honest with you.. I don't see any reason of having that.. buttons are more than enough :) But if you are about to have an example/demo.. have it right!

**Comment by FarhadG** [comment]
Just a concept :) but thanks for the input, @lipis.

**Comment by lipis** [comment]
Good luck :)

**Comment by FarhadG** [comment]
Just added a simple close button (if that helps any).

I'd love the help for some nice themes.
